---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
    ip_addr: "{{ new_node_host }}"
    new_node_fqdn: "{{ new_node_host }}.{{ domain_name }}"
  tasks: 
  - name: add nodes to inventory
    add_host:
      hostname: "{{ bastion_host }}"
      ansible_ssh_user: "{{ bastion_ssh_user }}"
      ansible_ssh_pass: "{{ bastion_ssh_pass }}"
      groupname: bastion
  - name: add nodes to inventory
    add_host:
      hostname: "{{ new_node_fqdn }}"
      ansible_ssh_user: "{{ new_node_ssh_user }}"
      ansible_ssh_pass: "{{ new_node_ssh_pass }}"
      groupname: new_node

- hosts: all
  remote_user: "{{ bastion_ssh_user }}"
  roles:
    - {role: 'ocp-config-scale'}
    - {role: 'ocp-scaleup'}
