---

  - name: add nodes to inventory
    add_host:
      hostname: "{{ bastion_host }}"
      ansible_ssh_user: "{{ bastion_ssh_user }}"
      ansible_ssh_pass: "{{ bastion_ssh_pass }}"
      groupname: bastion
    when: "'localhost' in group_names" 

  - name: add nodes to inventory
    add_host:
      hostname: "{{ new_node_fqdn }}"
      ansible_ssh_user: "{{ new_node_ssh_user }}"
      ansible_ssh_pass: "{{ new_node_ssh_pass }}"
      groupname: new_node
    when: "'localhost' in group_names" 

  - name: add newnodes line
    lineinfile:
      dest: /etc/ansible/hosts
      state: present
      insertafter: '^nodes'
      line: 'new_nodes'
    when: "'bastion' in group_names"      

  - name: add newnodes block
    blockinfile:
      insertafter: EOF
      path: /etc/ansible/hosts
      content: |
        [new_nodes]
        {{ new_node_fqdn }} openshift_node_labels="{'type': 'app'}" openshift_hostname={{ new_node_fqdn }} openshift_ip={{ new_node_ip }} openshift_public_ip={{ new_node_ip }}
    when: "'bastion' in group_names"      



